name: webnotify
description: Action for notifying web updates with LINE Notify
author: Laddge
branding:
  icon: clock
  color: green
inputs:
  targets:
    description: newline delimited targets
    required: true
  line_token:
    description: access token of LINE Notify
    required: true
  timezone:
    description: timezone
runs:
  using: composite
  steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml
      shell: bash

    - name: Run script
      env:
        TARGETS: ${{ inputs.targets }}
        LINE_TOKEN: ${{ inputs.line_token }}
        TZ: ${{ inputs.timezone }}
      run: |
        python $GITHUB_ACTION_PATH/task.py
      shell: bash

    - name: commit & push
      run: |
        git add -N .
        if ! git diff --exit-code --quiet
        then
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m 'update data'
          git push
        fi
      shell: bash
